### ISSUE TITLE
Nightly builds started failing on 2023-01-16

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/conda-forge-nightly-controller#1]
A few things:

* Both the [tiledb](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3935471954/jobs/6731177769) and [tiledb-py](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3935680952) jobs failed back on Jan 16th. It was during the rerendering step, which was unexpected. I'm hoping it's spurious, but I have to investigate further to diagnose the problem

* Both workflows have been stopped completely due to the [GitHub Actions policy](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) of automatically disabling scheduled workflows after 60 days of inactivity in the repo. I loathe this policy, as this affects many of my other projects as well where I create a scheduled job to notify me if an external dependency breaks my software
    > This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.
    * I'm not sure what we can do to prevent this besides manually re-renabling every 60 days. One alternative is we could have the workflow push a dummy commit. GitHub Actions knows when a commit is made by a workflow, but based on anecdotal evidence from one of my other repos, I think that may be sufficient to qualify as "activity"

* This is a good reminder that I should update the workflows to automatically open an Issue on failure. I already watch all the events on this repo, but since I don't have write access, there is no way for me to get notified about a failed build. Note that this is simpler than my related to-do item of opening an Issue for a failed feedstock build on Azure (since that happens on a separate repo on a separate CI platform)

**Action items:**

- [x] John: Diagnose rerendering error
- [x] @shaunrd0 or @ihnorton: Go [here](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/workflows/tiledb.yml) and [here](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/workflows/tiledb-py.yml), and click each button to re-enable both builds
- [x] John: update pipeline to open Issue for failed nightly build #2 
- [x] John: update pipeline to regularly push a dummy commit at some interval #3

**Comment by shaunrd0** [comment]
Thanks John, I've re-enabled these workflows for you. If there's anything else I can do here please let me know, happy to help.

**Comment by jdblischak** [comment]
I believe the source of the error is the recent update in setuptools 66.0 that made it more strict to allowable version strings: https://github.com/pypa/setuptools/issues/3772

```sh
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '3.8.* *_cpython'
```

I confirmed that the most recent [successful build](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3926541815/jobs/6712346390#step:12:505) used setuptools 65.6.3 and the [failed build](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3935471954/jobs/6731177769#step:12:505) used setuptools 6.66.0

But still unsure how to fix it. The discussion in the setuptools repo is mostly fixing the version strings of system Python packages installed by APT, which doesn't apply to us. We're already using a virtual (conda) env, which is the recommended workaround. And the upstream feedstocks don't appear to have this problem (yet, I guess), so why are we experiencing it?

**Comment by jdblischak** [comment]
Found it!

The Python pins in conda-forge-pinning are incompatible with setuptools 66+

https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3973

4 days ago they pushed repodata patches to pin `setuptools <66.0.0a` for the conda-build binaries on anaconda.org

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/387

Since these changes should by synced by now, the nightly builds should pass tonight 🤞

**Comment by jdblischak** [comment]
I confirmed that setuptools 65.6.3 is installed when running locally:

```sh
bash run-local-tiledb.sh
mamba list -n env-nightlies-tiledb setuptools
## # Name                    Version                   Build  Channel
## setuptools                65.6.3             pyhd8ed1ab_0    conda-forge

bash run-local-tiledb-py.sh
## error: failed to push some refs to 'https://github.com/TileDB-Inc/tiledb-py-feedstock.git'
mamba list -n env-nightlies-tiledb-py setuptools
## # Name                    Version                   Build  Channel
## setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
## setuptools-scm            7.1.0              pyhd8ed1ab_0    conda-forge
```

The failure when updating TileDB-Py is irrelevant. I don't have write access to [TileDB-Inc/tiledb-py-feedstock](https://github.com/TileDB-Inc/tiledb-py-feedstock), and it happens to be a few commits behind the upstream conda-forge feedstock (whereas [TileDB-Inc/tiledb-feedstock](https://github.com/TileDB-Inc/tiledb-feedstock) is in sync)

**Comment by jdblischak** [comment]
Good news. Now that Shaun re-enabled the workflows and the conda-forge team patched conda-build to use `setuptools<66`, the scheduled nightly builds both passed

* [tiledb](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3992413705/jobs/6848231908)
* [tiledb-py](https://github.com/TileDB-Inc/conda-forge-nightly-controller/actions/runs/3992636635/jobs/6848661536)

The tiledb feedstock Azure build [passed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=29525&view=results) and uploaded binaries for [2.15.0.2023_01_23](https://anaconda.org/tiledb/tiledb/files?version=2.15.0.2023_01_23&channel=nightlies). However, the tiledb-py feedstock Azure builds all [failed](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=29528&view=results), but I think this is a known issue since the nightly builds on the source repo have also been [failing](https://github.com/TileDB-Inc/TileDB-Py/actions/workflows/daily-test-build.yml), eg https://github.com/TileDB-Inc/TileDB-Py/issues/1584
