### ISSUE TITLE
Job to delete older binaries from anaconda.org

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/conda-forge-nightly-controller#5]
The nightly binaries use up a lot of storage space on anaconda.org. The plan is for me to write a GitHub Actions workflow that will run every Sunday and delete all nightly binaries that are more than a week old.

cc: @ihnorton

**Comment by jdblischak** [comment]
I have a workflow on my fork that successfully deleted old nightlies from my personal anaconda.org account. I'll clean it up and send a PR later this week

https://github.com/jdblischak/conda-forge-nightly-controller/actions/runs/4472591640/jobs/7858936839#step:5:15
https://github.com/jdblischak/conda-forge-nightly-controller/blob/delete-old-nightlies/.github/workflows/delete-old-nightlies.yml

**Comment by ihnorton** [comment]
Thanks @jdblischak
